#version: '3.8'
#
#services:
#  db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    container_name: mssql2022
#    environment:
#      SA_PASSWORD: "<YourStrong!Passw0rd>"
#      ACCEPT_EULA: "Y"
#    ports:
#      - "1433:1433"
#    networks:
#      - mynetwork
#
#  app:
#    image:  mcr.microsoft.com/mssql/server:2022-latest
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;database=db
#      SPRING_DATASOURCE_USERNAME: sa
#      SPRING_DATASOURCE_PASSWORD: <YourStrong!Passw0rd>
#    networks:
#      - mynetwork
#
#networks:
#  mynetwork:
#    driver: bridge
#
#
